### ISSUE TITLE
Package specific files `ports.yaml`, `ports-lock.yaml`

### ISSUE THREAD

**Issue by kcauchy** [cports-io/ports#2]
Both files should be considered as ports required file.

You can use `ports init` to initialize the package files.

There may be the third file `ports-machine.yaml` (Name to be defined)

**Comment by kcauchy** [comment]
Our last project `c-package-manager` defined a very complex `ports.yaml`, which is not a good idea, because they are really hard to read. However, the compile details cannot be simply defined just by one simple file.

Therefore it is suggested to use a file to describe details. And it can be generated by machine, and should be considered as part of package descriptions.

**Comment by kcauchy** [comment]
A `ports.yaml` should be like this:

```yaml
name: My First Repo
version: 4.4.0.8800.alpha
dependencies:
  LLVM-Support: 3.8.0-alpha
```

For different platforms, the dependencies will be quite different. We described directly in `ports.yaml` before, that will make the `ports.yaml` too complex. Here, we will use another file to describe the complex compile conditions (maybe called as `ports-lock.yaml`:

```yaml
dependencies:
   LLVM-Support: 
      os: ['Windows:x86', 'Linux']
```

Then this will be quite clear to be compiled for all Windows systems, x86 only, and Linux operating system.

That definition will be very complex, we can provide a tool to manage it.
